name: Run Python Script

on:
  schedule:
    - cron: '0 9 * * *'  # Run every day at 9 AM Lisbon time (UTC +1)
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python author_alert.py
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}

    - name: Commit and push updated authors_articles.json
      run: |
       git config --global user.name "GitHub Actions"
       git config --global user.email "actions@github.com"
       git add .
       git commit -m "Update authors_articles.json with new articles"
       git push https://${{ secrets.PAT }}@github.com/DiogoCosta99/FT-Author-Watch.git

   
